version: '3.7'

services:
  policykit_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    command: bash -c "python3 metagov/manage.py makemigrations &&
      python3 metagov/manage.py migrate &&
      python3 metagov/manage.py collectstatic &&
      python3 metagov/manage.py runserver 0.0.0.0:8000"
    environment:
      - "POSTGRES_DB=metagov"
      - "RABBITMQ_USER=admin"
      - "DOCKER_ENV_CHECK=true"
      - "POSTGRES_HOST=database"
      - "POSTGRES_USER=postgres"
      - "RABBITMQ_PASSWORD=mypass"
      - "RABBITMQ_HOST=rabbitmq_server"
      - "POSTGRES_PASSWORD=supersecretpassword"
    ports:
      - "8000"
    depends_on:
      - database
      - rabbitmq_server
    networks:
      - monitoring

  database:
    container_name: postgresql
    image: postgres:alpine
    restart: always
    environment:
      - "POSTGRES_DB=metagov"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=supersecretpassword"
    ports:
      - "5432:5432"
    networks:
      - monitoring
    volumes:
      - policykit-database:/var/lib/postgresql/data:rw

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    volumes:
      - policykit-nginx-logs:/var/log/nginx
      - ./policykit/docker_data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./policykit/docker_data/nginx/privatekey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./policykit/docker_data/nginx/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
    networks:
      - monitoring

  rabbitmq_server:
    container_name: rabbitmq
    image: rabbitmq:3.9.13-management
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=mypass"
    ports:
      - "5672:5672"
      - "15673:15672"
    volumes:
      - policykit-rabbitmq:/var/lib/rabbitmq/
    networks:
      - monitoring

volumes:
  policykit-database:
  policykit-rabbitmq:
  policykit-nginx-logs:

networks:
  monitoring: